[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d

# Command for auto up
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root

# Number of worker processes
numprocs=1
redirect_stderr=true

# Logs
stdout_logfile=/var/www/storage/logs/worker.log
stopwaitsecs=3600